#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_PATCH 1

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define FILE_VERSION_STR STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) ".0"
#define PRODUCT_VERSION_STR STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) ".0"

#endif // VERSION_H
